# Generated by Django 6.0.2 on 2026-02-06 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Immunobiological',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('batch_number', models.CharField(max_length=100)),
                ('expiration_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('contraindications', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Immunobiological',
                'verbose_name_plural': 'Immunobiologicals',
                'ordering': ['expiration_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('cns', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cartão SUS (CNS)')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Mãe')),
                ('gender', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sexo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineSchedule',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('vaccine_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('age_group', models.CharField(max_length=50)),
                ('min_age_in_days', models.IntegerField()),
                ('max_age_in_days', models.IntegerField(blank=True, null=True)),
                ('dose_number', models.IntegerField()),
                ('dose_description', models.CharField(max_length=255)),
                ('diseases_prevented', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Vaccine Schedule',
                'verbose_name_plural': 'Vaccine Schedules',
                'ordering': ['min_age_in_days', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('immunobiological', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='api.immunobiological')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='api.patient', verbose_name='Paciente')),
                ('vaccine_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='api.vaccineschedule')),
            ],
            options={
                'verbose_name': 'Registro de Vacinação',
                'verbose_name_plural': 'Registros de Vacinação',
                'ordering': ['-application_date'],
            },
        ),
    ]
