# Generated by Django 6.0.2 on 2026-02-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationrecord',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
