# Generated by Django 6.0.2 on 2026-02-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Immunobiological',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('batch_number', models.CharField(max_length=100)),
                ('expiration_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('contraindications', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Immunobiological',
                'verbose_name_plural': 'Immunobiologicals',
                'ordering': ['expiration_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VaccineSchedule',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('vaccine_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('age_group', models.CharField(max_length=50)),
                ('min_age_in_days', models.IntegerField()),
                ('max_age_in_days', models.IntegerField(blank=True, null=True)),
                ('dose_number', models.IntegerField()),
                ('dose_description', models.CharField(max_length=255)),
                ('diseases_prevented', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Vaccine Schedule',
                'verbose_name_plural': 'Vaccine Schedules',
                'ordering': ['min_age_in_days', 'id'],
            },
        ),
    ]
