# Generated by Django 6.0.2 on 2026-02-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_immunobiological_vaccineschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccineschedule',
            name='vaccine_id',
            field=models.CharField(max_length=100),
        ),
    ]
