# Generated by Django 6.0.2 on 2026-02-05 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_vaccineschedule_vaccine_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=255, verbose_name='ID do Paciente')),
                ('application_date', models.DateTimeField(verbose_name='Data da Aplicação')),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('immunobiological', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='api.immunobiological')),
                ('vaccine_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='api.vaccineschedule')),
            ],
            options={
                'verbose_name': 'Registro de Vacinação',
                'verbose_name_plural': 'Registros de Vacinação',
                'ordering': ['-application_date'],
            },
        ),
    ]
