# Generated by Django 6.0.2 on 2026-02-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_vaccinationrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunobiological',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='immunobiological',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
